// @generated by bffi codegen - do not edit.
// Source module: bunframe
// Wrapper style: specialized (hoisted symbols and out slots,
// inline argument encoding and return decoding per ABI kind).

import { dlopen, ptr } from "bun:ffi";
import {
  type ApiOf,
  ErrorCode,
  type FfiLib,
  type FfiSymbol,
  type ModuleJson,
  type TsOf,
  buildDeclarations,
  decodeAt,
  encodeValue,
  jsToWire,
  makeReadBuffer,
  makeTakeError,
  tablesOf,
  wireToJs,
} from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "bunframe",
  "abiVersion": 1,
  "exportsHash": "8454069739320850434",
  "functions": [
    {
      "name": "window_open",
      "export": "bffi_window_open",
      "docs": [
        "Opens a window described by `config` (inline `html` or a `url`,",
        "title, size, min size, decorations, transparency, position,",
        "maximized/visible/always-on-top/skip-taskbar, devtools, `bf`",
        "asset serving) and returns its opaque handle. The first call",
        "spawns the dedicated loop thread (winit event loop + window +",
        "wry surface live there); the Bun thread only waits, bounded, for",
        "the creation reply. The window's events stream opens with the",
        "window - pull it through [`window_events`]."
      ],
      "params": [
        {
          "name": "config",
          "ts": "WindowConfig",
          "abi": "ptr_len"
        }
      ],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "window_events",
      "export": "bffi_window_events",
      "docs": [
        "The handle of the window's events stream: JSON events",
        "(`resized` / `focused` / `close-denied` / `closed`) pulled",
        "through the stream API. The stream exists from window creation",
        "and completes when the window closes."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "window_close",
      "export": "bffi_window_close",
      "docs": [
        "Closes the window behind `handle` (also the title-bar X path,",
        "minus the veto): the loop thread drops the window and exits when",
        "it was the last one - then [`window_poll_exit`] flips to `true`.",
        "The close-veto callback (when bound) is NOT consulted on this",
        "programmatic close."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_eval",
      "export": "bffi_window_eval",
      "docs": [
        "Evaluates `js` in the window behind `handle` (proxied onto the",
        "loop thread; fire-and-forget - the script's result stays in the",
        "page)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "js",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_set_title",
      "export": "bffi_window_set_title",
      "docs": [
        "Sets the window title."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "title",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_set_size",
      "export": "bffi_window_set_size",
      "docs": [
        "Sets the window size (logical pixels)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "width",
          "ts": "number",
          "abi": "u32"
        },
        {
          "name": "height",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_set_position",
      "export": "bffi_window_set_position",
      "docs": [
        "Sets the window position (logical pixels - the same space as the",
        "`x`/`y` open config)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "x",
          "ts": "number",
          "abi": "i32"
        },
        {
          "name": "y",
          "ts": "number",
          "abi": "i32"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_center",
      "export": "bffi_window_center",
      "docs": [
        "Centers the window on its current monitor. Best-effort: window",
        "ops are fire-and-forget, so a window without a monitor simply",
        "stays put (the center math is PHYSICAL and manual - winit 0.30",
        "has no `Window::center`)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_set_min_size",
      "export": "bffi_window_set_min_size",
      "docs": [
        "Sets the minimum window size (logical pixels). `None` leaves the",
        "axis unconstrained; both `None` clears the constraint entirely."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "width",
          "ts": "number | null",
          "abi": "opt_number"
        },
        {
          "name": "height",
          "ts": "number | null",
          "abi": "opt_number"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_set_resizable",
      "export": "bffi_window_set_resizable",
      "docs": [
        "Sets whether the window is resizable."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "on",
          "ts": "boolean",
          "abi": "bool"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_set_decorations",
      "export": "bffi_window_set_decorations",
      "docs": [
        "Sets whether the window has decorations."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "on",
          "ts": "boolean",
          "abi": "bool"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_set_always_on_top",
      "export": "bffi_window_set_always_on_top",
      "docs": [
        "Sets whether the window is always on top."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "on",
          "ts": "boolean",
          "abi": "bool"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_set_visible",
      "export": "bffi_window_set_visible",
      "docs": [
        "Shows or hides the window."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "on",
          "ts": "boolean",
          "abi": "bool"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_focus",
      "export": "bffi_window_focus",
      "docs": [
        "Gives the window keyboard focus."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_maximize",
      "export": "bffi_window_maximize",
      "docs": [
        "Maximizes the window."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_unmaximize",
      "export": "bffi_window_unmaximize",
      "docs": [
        "Restores a maximized window."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_minimize",
      "export": "bffi_window_minimize",
      "docs": [
        "Minimizes the window."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_is_maximized",
      "export": "bffi_window_is_maximized",
      "docs": [
        "Whether the window behind `handle` is currently maximized",
        "(queried on the loop thread; the Bun thread waits, bounded, for",
        "the answer)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "boolean",
        "abi": "bool"
      },
      "out": "bool"
    },
    {
      "name": "window_is_visible",
      "export": "bffi_window_is_visible",
      "docs": [
        "Whether the window behind `handle` is currently visible."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "boolean",
        "abi": "bool"
      },
      "out": "bool"
    },
    {
      "name": "window_inner_size",
      "export": "bffi_window_inner_size",
      "docs": [
        "The inner (webview viewport) size of the window behind",
        "`handle`, in PHYSICAL pixels."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "WindowSize",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "window_position",
      "export": "bffi_window_position",
      "docs": [
        "The outer-frame position of the window behind `handle`, in",
        "PHYSICAL pixels."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "WindowPosition",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "window_open_devtools",
      "export": "bffi_window_open_devtools",
      "docs": [
        "Opens the webview devtools of the window."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_bind_ipc",
      "export": "bffi_window_bind_ipc",
      "docs": [
        "Wires the IPC roundtrip of the window behind `handle` to a JS",
        "handler: `ipc` is a JS-BOUND callback handle with the signature",
        "`unit(str)` - the request body arrives as the `cstring`",
        "argument; the handler answers through [`window_ipc_reply`].",
        "",
        "The first bind spawns the window's IPC worker thread: page",
        "messages queue on it, so the loop thread never parks inside the",
        "wry ipc handler and calls can pipeline. Rebinding keeps the",
        "worker and just swaps the callback handle (read fresh per",
        "message)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "ipc",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_ipc_reply",
      "export": "bffi_window_ipc_reply",
      "docs": [
        "The IPC message box, JS side: stores the reply JSON (embedded",
        "into the resolve script verbatim, so it MUST be valid JSON).",
        "Called by the bound callback before it returns."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "reply",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_bind_close",
      "export": "bffi_window_bind_close",
      "docs": [
        "Wires the close-veto check of the window behind `handle` to a JS",
        "callback: `veto` is a JS-BOUND callback handle with the",
        "signature `bool(str)`. On a title-bar close request the loop",
        "thread passes the event JSON and waits (up to 10s): the callback",
        "returns `true` to ALLOW the close, `false` to deny it",
        "(a `close-denied` event is pushed). Any error or timeout",
        "FAILS OPEN (the close proceeds) - a hung backend must not make",
        "a window unclosable."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "veto",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "window_poll_exit",
      "export": "bffi_window_poll_exit",
      "docs": [
        "Whether the loop thread has finished (after [`app_quit`], or a",
        "loop-thread crash)."
      ],
      "params": [],
      "ret": {
        "ts": "boolean",
        "abi": "bool"
      },
      "out": "bool"
    },
    {
      "name": "app_quit",
      "export": "bffi_app_quit",
      "docs": [
        "Exits the loop thread explicitly (the app shell decision): the",
        "process is done with native windows afterwards - a later",
        "[`window_open`] reports `LoopNotRunning`. Idempotent."
      ],
      "params": [],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "loop_pump",
      "export": "bffi_loop_pump",
      "docs": [
        "The non-blocking drain the JS side calls while native threads",
        "wait (`pumpUntil` from the npm side): the marshalled callback",
        "invocation executes here, on the bound JS thread."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    }
  ],
  "classes": [],
  "records": [
    {
      "name": "WindowConfig",
      "docs": [
        "The open request: everything optional (`None` rides the",
        "`TAG_UNIT` wire byte and arrives as `null` on the JS side).",
        "Exactly one of `url`/`html` should be set; `html` wins if both",
        "are (wry ignores `url` when `html` is present). Sizes and",
        "positions are LOGICAL pixels. Without `x`/`y` the OS picks the",
        "position."
      ],
      "fields": [
        {
          "name": "url",
          "docs": [
            "The URL to load."
          ],
          "ts": "string | null"
        },
        {
          "name": "html",
          "docs": [
            "The inline HTML to load (overrides `url`)."
          ],
          "ts": "string | null"
        },
        {
          "name": "title",
          "docs": [
            "The window title (`\"bunframe\"` when `None`)."
          ],
          "ts": "string | null"
        },
        {
          "name": "width",
          "docs": [
            "The window width (logical px; `1024` when `None`)."
          ],
          "ts": "number | null"
        },
        {
          "name": "height",
          "docs": [
            "The window height (logical px; `768` when `None`)."
          ],
          "ts": "number | null"
        },
        {
          "name": "min_width",
          "docs": [
            "The minimum width (logical px)."
          ],
          "ts": "number | null"
        },
        {
          "name": "min_height",
          "docs": [
            "The minimum height (logical px)."
          ],
          "ts": "number | null"
        },
        {
          "name": "resizable",
          "docs": [
            "Whether the window is resizable (`true` when `None`)."
          ],
          "ts": "boolean | null"
        },
        {
          "name": "decorations",
          "docs": [
            "Whether the window has decorations (`true` when `None`)."
          ],
          "ts": "boolean | null"
        },
        {
          "name": "transparent",
          "docs": [
            "Whether the window/webview background is transparent."
          ],
          "ts": "boolean | null"
        },
        {
          "name": "maximized",
          "docs": [
            "Whether the window opens maximized."
          ],
          "ts": "boolean | null"
        },
        {
          "name": "visible",
          "docs": [
            "Whether the window is visible on creation (`true` when",
            "`None`)."
          ],
          "ts": "boolean | null"
        },
        {
          "name": "x",
          "docs": [
            "The window position, logical x."
          ],
          "ts": "number | null"
        },
        {
          "name": "y",
          "docs": [
            "The window position, logical y."
          ],
          "ts": "number | null"
        },
        {
          "name": "devtools",
          "docs": [
            "Whether devtools are enabled."
          ],
          "ts": "boolean | null"
        },
        {
          "name": "always_on_top",
          "docs": [
            "Whether the window is always on top."
          ],
          "ts": "boolean | null"
        },
        {
          "name": "skip_taskbar",
          "docs": [
            "Whether the window is hidden from the taskbar (Windows)."
          ],
          "ts": "boolean | null"
        },
        {
          "name": "asset_root",
          "docs": [
            "The asset directory served to this window through the `bf`",
            "custom protocol (set at creation; wry binds custom protocols",
            "at webview build time). The page loads `bf://localhost/<rel",
            "-path>` - wry maps it to `http://bf.localhost/<rel-path>` on",
            "Windows, so the page sees `http://bf.localhost/...` origins:",
            "spell URLs `bf://localhost/...` in app code. `/` serves",
            "`index.html`."
          ],
          "ts": "string | null"
        }
      ]
    },
    {
      "name": "WindowSize",
      "docs": [
        "The inner (webview viewport) size of a window, in PHYSICAL",
        "pixels (the [`window_inner_size`] reply)."
      ],
      "fields": [
        {
          "name": "width",
          "docs": [
            "Width, physical pixels."
          ],
          "ts": "number"
        },
        {
          "name": "height",
          "docs": [
            "Height, physical pixels."
          ],
          "ts": "number"
        }
      ]
    },
    {
      "name": "WindowPosition",
      "docs": [
        "The outer-frame position of a window, in PHYSICAL pixels (the",
        "[`window_position`] reply)."
      ],
      "fields": [
        {
          "name": "x",
          "docs": [
            "X, physical pixels."
          ],
          "ts": "number"
        },
        {
          "name": "y",
          "docs": [
            "Y, physical pixels."
          ],
          "ts": "number"
        }
      ]
    }
  ],
  "enums": [],
  "errors": [
    {
      "name": "BunframeError",
      "docs": [
        "The domain error of the crate (the typed errors table in",
        "[`module_def`]; codes `0x1001..`)."
      ],
      "variants": [
        {
          "name": "InvalidHandle",
          "docs": [
            "The handle is null, stale, or belongs to a closed window."
          ],
          "code": "0x1001",
          "fields": []
        },
        {
          "name": "LoopNotRunning",
          "docs": [
            "The loop thread is not running (it stopped or never started)."
          ],
          "code": "0x1002",
          "fields": []
        },
        {
          "name": "CreateFailed",
          "docs": [
            "The window/webview creation failed on the loop thread."
          ],
          "code": "0x1003",
          "fields": [
            {
              "name": "message",
              "docs": [
                "The failure message."
              ],
              "ts": "string"
            }
          ]
        },
        {
          "name": "OperationFailed",
          "docs": [
            "A window operation failed on the loop thread."
          ],
          "code": "0x1004",
          "fields": [
            {
              "name": "message",
              "docs": [
                "The failure message."
              ],
              "ts": "string"
            }
          ]
        },
        {
          "name": "InvalidCallback",
          "docs": [
            "A bound callback handle is null or has the wrong signature."
          ],
          "code": "0x1005",
          "fields": [
            {
              "name": "message",
              "docs": [
                "The reason the handle was rejected."
              ],
              "ts": "string"
            }
          ]
        },
        {
          "name": "EventsUnavailable",
          "docs": [
            "The events stream of the window is not available."
          ],
          "code": "0x1006",
          "fields": []
        }
      ]
    }
  ]
} as const satisfies ModuleJson;

/**
 * The open request: everything optional (`None` rides the
 * `TAG_UNIT` wire byte and arrives as `null` on the JS side).
 * Exactly one of `url`/`html` should be set; `html` wins if both
 * are (wry ignores `url` when `html` is present). Sizes and
 * positions are LOGICAL pixels. Without `x`/`y` the OS picks the
 * position.
 */
export type WindowConfig = TsOf<"WindowConfig", typeof moduleJson>;
/**
 * The inner (webview viewport) size of a window, in PHYSICAL
 * pixels (the [`window_inner_size`] reply).
 */
export type WindowSize = TsOf<"WindowSize", typeof moduleJson>;
/**
 * The outer-frame position of a window, in PHYSICAL pixels (the
 * [`window_position`] reply).
 */
export type WindowPosition = TsOf<"WindowPosition", typeof moduleJson>;

/** The explicit low-level loader: opens the native library at
 * `libraryPath` and returns the typed API. Passing a raw binary
 * path is a trust decision - the pipeline resolves platform
 * packages by default. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  const lib: FfiLib = dlopen(libraryPath, buildDeclarations(moduleJson)).symbols as FfiLib;
  const takeError = makeTakeError(lib);
  const readBuffer = makeReadBuffer(lib);
  const sym = (name: string): FfiSymbol => {
    const found = lib[name];
    if (typeof found !== "function") {
      throw new Error("missing export: " + name);
    }
    return found;
  };
  const tables = tablesOf(moduleJson);
  const wireBytes = (ts: string, value: unknown, ctx: string): Uint8Array => {
    const record = jsToWire(tables, ts, value, ctx);
    const bytes: number[] = [];
    encodeValue(bytes, record);
    return new Uint8Array(bytes);
  };
  const out_window_open = new BigUint64Array(1);
  const sym_window_open = sym("bffi_window_open");
  const fn_window_open = function (a0: TsOf<"WindowConfig", typeof moduleJson>): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("window_open: expected 1 argument(s), got " + arguments.length);
    }
    const wire_window_open_config = wireBytes("WindowConfig", a0, "window_open(config)");
    const status = Number(sym_window_open(wire_window_open_config.length > 0 ? ptr(wire_window_open_config) : null, wire_window_open_config.length, out_window_open));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_open failed: " + String(status));
    }
    return (out_window_open[0] ?? 0n);
  };
  const out_window_events = new BigUint64Array(1);
  const sym_window_events = sym("bffi_window_events");
  const fn_window_events = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("window_events: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_events(a0, out_window_events));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_events failed: " + String(status));
    }
    return (out_window_events[0] ?? 0n);
  };
  const sym_window_close = sym("bffi_window_close");
  const fn_window_close = function (a0: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 1) {
      throw new Error("window_close: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_close(a0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_close failed: " + String(status));
    }
  };
  const sym_window_eval = sym("bffi_window_eval");
  const fn_window_eval = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"string", typeof moduleJson>): void {
    if (arguments.length !== 2) {
      throw new Error("window_eval: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_eval(a0, a1));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_eval failed: " + String(status));
    }
  };
  const sym_window_set_title = sym("bffi_window_set_title");
  const fn_window_set_title = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"string", typeof moduleJson>): void {
    if (arguments.length !== 2) {
      throw new Error("window_set_title: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_set_title(a0, a1));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_set_title failed: " + String(status));
    }
  };
  const sym_window_set_size = sym("bffi_window_set_size");
  const fn_window_set_size = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"number", typeof moduleJson>, a2: TsOf<"number", typeof moduleJson>): void {
    if (arguments.length !== 3) {
      throw new Error("window_set_size: expected 3 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_set_size(a0, a1, a2));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_set_size failed: " + String(status));
    }
  };
  const sym_window_set_position = sym("bffi_window_set_position");
  const fn_window_set_position = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"number", typeof moduleJson>, a2: TsOf<"number", typeof moduleJson>): void {
    if (arguments.length !== 3) {
      throw new Error("window_set_position: expected 3 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_set_position(a0, a1, a2));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_set_position failed: " + String(status));
    }
  };
  const sym_window_center = sym("bffi_window_center");
  const fn_window_center = function (a0: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 1) {
      throw new Error("window_center: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_center(a0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_center failed: " + String(status));
    }
  };
  const sym_window_set_min_size = sym("bffi_window_set_min_size");
  const fn_window_set_min_size = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"number | null", typeof moduleJson>, a2: TsOf<"number | null", typeof moduleJson>): void {
    if (arguments.length !== 3) {
      throw new Error("window_set_min_size: expected 3 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_set_min_size(a0, a1, a2));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_set_min_size failed: " + String(status));
    }
  };
  const sym_window_set_resizable = sym("bffi_window_set_resizable");
  const fn_window_set_resizable = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"boolean", typeof moduleJson>): void {
    if (arguments.length !== 2) {
      throw new Error("window_set_resizable: expected 2 argument(s), got " + arguments.length);
    }
    if (typeof a1 !== "boolean") {
      throw new TypeError("window_set_resizable(on): expected boolean");
    }
    const status = Number(sym_window_set_resizable(a0, a1 ? 1 : 0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_set_resizable failed: " + String(status));
    }
  };
  const sym_window_set_decorations = sym("bffi_window_set_decorations");
  const fn_window_set_decorations = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"boolean", typeof moduleJson>): void {
    if (arguments.length !== 2) {
      throw new Error("window_set_decorations: expected 2 argument(s), got " + arguments.length);
    }
    if (typeof a1 !== "boolean") {
      throw new TypeError("window_set_decorations(on): expected boolean");
    }
    const status = Number(sym_window_set_decorations(a0, a1 ? 1 : 0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_set_decorations failed: " + String(status));
    }
  };
  const sym_window_set_always_on_top = sym("bffi_window_set_always_on_top");
  const fn_window_set_always_on_top = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"boolean", typeof moduleJson>): void {
    if (arguments.length !== 2) {
      throw new Error("window_set_always_on_top: expected 2 argument(s), got " + arguments.length);
    }
    if (typeof a1 !== "boolean") {
      throw new TypeError("window_set_always_on_top(on): expected boolean");
    }
    const status = Number(sym_window_set_always_on_top(a0, a1 ? 1 : 0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_set_always_on_top failed: " + String(status));
    }
  };
  const sym_window_set_visible = sym("bffi_window_set_visible");
  const fn_window_set_visible = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"boolean", typeof moduleJson>): void {
    if (arguments.length !== 2) {
      throw new Error("window_set_visible: expected 2 argument(s), got " + arguments.length);
    }
    if (typeof a1 !== "boolean") {
      throw new TypeError("window_set_visible(on): expected boolean");
    }
    const status = Number(sym_window_set_visible(a0, a1 ? 1 : 0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_set_visible failed: " + String(status));
    }
  };
  const sym_window_focus = sym("bffi_window_focus");
  const fn_window_focus = function (a0: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 1) {
      throw new Error("window_focus: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_focus(a0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_focus failed: " + String(status));
    }
  };
  const sym_window_maximize = sym("bffi_window_maximize");
  const fn_window_maximize = function (a0: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 1) {
      throw new Error("window_maximize: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_maximize(a0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_maximize failed: " + String(status));
    }
  };
  const sym_window_unmaximize = sym("bffi_window_unmaximize");
  const fn_window_unmaximize = function (a0: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 1) {
      throw new Error("window_unmaximize: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_unmaximize(a0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_unmaximize failed: " + String(status));
    }
  };
  const sym_window_minimize = sym("bffi_window_minimize");
  const fn_window_minimize = function (a0: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 1) {
      throw new Error("window_minimize: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_minimize(a0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_minimize failed: " + String(status));
    }
  };
  const out_window_is_maximized = new Uint8Array(1);
  const sym_window_is_maximized = sym("bffi_window_is_maximized");
  const fn_window_is_maximized = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"boolean", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("window_is_maximized: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_is_maximized(a0, out_window_is_maximized));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_is_maximized failed: " + String(status));
    }
    return (out_window_is_maximized[0] ?? 0) !== 0;
  };
  const out_window_is_visible = new Uint8Array(1);
  const sym_window_is_visible = sym("bffi_window_is_visible");
  const fn_window_is_visible = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"boolean", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("window_is_visible: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_is_visible(a0, out_window_is_visible));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_is_visible failed: " + String(status));
    }
    return (out_window_is_visible[0] ?? 0) !== 0;
  };
  const out_window_inner_size = new BigUint64Array(1);
  const sym_window_inner_size = sym("bffi_window_inner_size");
  const fn_window_inner_size = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"WindowSize", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("window_inner_size: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_inner_size(a0, out_window_inner_size));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_inner_size failed: " + String(status));
    }
    if (typeof ((out_window_inner_size[0] ?? 0n)) !== "bigint") {
      throw new TypeError("window_inner_size: expected a buffer handle");
    }
    const bytes_window_inner_size = readBuffer((out_window_inner_size[0] ?? 0n));
    return wireToJs(tables, "WindowSize", decodeAt(bytes_window_inner_size, 0).value, "window_inner_size()") as TsOf<"WindowSize", typeof moduleJson>;
  };
  const out_window_position = new BigUint64Array(1);
  const sym_window_position = sym("bffi_window_position");
  const fn_window_position = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"WindowPosition", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("window_position: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_position(a0, out_window_position));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_position failed: " + String(status));
    }
    if (typeof ((out_window_position[0] ?? 0n)) !== "bigint") {
      throw new TypeError("window_position: expected a buffer handle");
    }
    const bytes_window_position = readBuffer((out_window_position[0] ?? 0n));
    return wireToJs(tables, "WindowPosition", decodeAt(bytes_window_position, 0).value, "window_position()") as TsOf<"WindowPosition", typeof moduleJson>;
  };
  const sym_window_open_devtools = sym("bffi_window_open_devtools");
  const fn_window_open_devtools = function (a0: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 1) {
      throw new Error("window_open_devtools: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_open_devtools(a0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_open_devtools failed: " + String(status));
    }
  };
  const sym_window_bind_ipc = sym("bffi_window_bind_ipc");
  const fn_window_bind_ipc = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 2) {
      throw new Error("window_bind_ipc: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_bind_ipc(a0, a1));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_bind_ipc failed: " + String(status));
    }
  };
  const sym_window_ipc_reply = sym("bffi_window_ipc_reply");
  const fn_window_ipc_reply = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"string", typeof moduleJson>): void {
    if (arguments.length !== 2) {
      throw new Error("window_ipc_reply: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_ipc_reply(a0, a1));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_ipc_reply failed: " + String(status));
    }
  };
  const sym_window_bind_close = sym("bffi_window_bind_close");
  const fn_window_bind_close = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 2) {
      throw new Error("window_bind_close: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_bind_close(a0, a1));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_bind_close failed: " + String(status));
    }
  };
  const out_window_poll_exit = new Uint8Array(1);
  const sym_window_poll_exit = sym("bffi_window_poll_exit");
  const fn_window_poll_exit = function (): TsOf<"boolean", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("window_poll_exit: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_window_poll_exit(out_window_poll_exit));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_window_poll_exit failed: " + String(status));
    }
    return (out_window_poll_exit[0] ?? 0) !== 0;
  };
  const sym_app_quit = sym("bffi_app_quit");
  const fn_app_quit = function (): void {
    if (arguments.length !== 0) {
      throw new Error("app_quit: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_app_quit());
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_app_quit failed: " + String(status));
    }
  };
  const out_loop_pump = new BigUint64Array(1);
  const sym_loop_pump = sym("bffi_loop_pump");
  const fn_loop_pump = function (): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("loop_pump: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_loop_pump(out_loop_pump));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_loop_pump failed: " + String(status));
    }
    return (out_loop_pump[0] ?? 0n);
  };
  return {
    "window_open": fn_window_open,
    "window_events": fn_window_events,
    "window_close": fn_window_close,
    "window_eval": fn_window_eval,
    "window_set_title": fn_window_set_title,
    "window_set_size": fn_window_set_size,
    "window_set_position": fn_window_set_position,
    "window_center": fn_window_center,
    "window_set_min_size": fn_window_set_min_size,
    "window_set_resizable": fn_window_set_resizable,
    "window_set_decorations": fn_window_set_decorations,
    "window_set_always_on_top": fn_window_set_always_on_top,
    "window_set_visible": fn_window_set_visible,
    "window_focus": fn_window_focus,
    "window_maximize": fn_window_maximize,
    "window_unmaximize": fn_window_unmaximize,
    "window_minimize": fn_window_minimize,
    "window_is_maximized": fn_window_is_maximized,
    "window_is_visible": fn_window_is_visible,
    "window_inner_size": fn_window_inner_size,
    "window_position": fn_window_position,
    "window_open_devtools": fn_window_open_devtools,
    "window_bind_ipc": fn_window_bind_ipc,
    "window_ipc_reply": fn_window_ipc_reply,
    "window_bind_close": fn_window_bind_close,
    "window_poll_exit": fn_window_poll_exit,
    "app_quit": fn_app_quit,
    "loop_pump": fn_loop_pump,
  };
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
